import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>OTP app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="fullscreen dead-center">
        <div className="flex flex-col gap-5 border rounded shadow-md w-11/12 max-w-lg py-8">
          <h1 className="text-3xl font-bold text-center">Welome to the app</h1>
          <div className="flex justify-center">
            <Link className="btn mx-3" href="/login">
              Login
            </Link>
            <Link className="btn btn-primary mx-3" href="/signup">
              Signup
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
